### ISSUE TITLE
Doubt regarding dataset_coco.json

### ISSUE THREAD

**Issue by Msknsngla** [davinhill/Convolution_Captioning#1]

**Comment by Msknsngla** [comment]
Could you please explain what does the dataset_coco.json contain and where can we find it?

**Comment by davinhill** [comment]
Hello, dataset_coco.json contains the training/validation dataset splits for MSCOCO that we used in our implementation, which we used to match https://arxiv.org/pdf/1711.09151.pdf

It can be downloaded here: http://cs.stanford.edu/people/karpathy/deepimagesent/caption_datasets.zip

**Comment by Msknsngla** [comment]
Thanks alot
